### ISSUE TITLE
MM Issues and Ideas

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1088]
Hello, I'm in the process of writing longer articles / a book with many MD files and came across a few topics. If you want me to split them into separate issues please let me know, but I didn't want to spam the tracker... thanks!

# MM Issues & Ideas

- [x] Make the tabs all equal width as long as there is space on the screen; this lets you close multiple tabs faster (many web browsers do this) by clicking on the same spot. When you have too many to fit on the screen, then make them as bigger / smaller depending on their filename (current behavior) NOTE: see https://github.com/RickStrahl/MarkdownMonster/issues/1090
- [x] opening a first level directory works with double click on a folder, subsequent levels only work with a click on the arrow. NOTE: see https://github.com/RickStrahl/MarkdownMonster/issues/1093
- [x] when clicking on a file and wanting to drag it up or down to another folder, MM (most of the time) selects the file above or below and moves that file instead. It seems that the dragging after selection takes a little time to start so that the file directly above / below the one you want is selected and dragged NOTE: see https://github.com/RickStrahl/MarkdownMonster/issues/1091
- [x] double clicking a file opens it twice (seems to only happen when it's the very first file opened); ask (prompt) before opening the same file twice. Also: sometimes the second copy is empty after closing one of them... I have never lost anything, but it's a little worrying nonetheless. NOTE: see https://github.com/RickStrahl/MarkdownMonster/issues/1092
- [x] I have a bash (create_book.sh) file that is plain text. MM should open non-MD text files directly or specify a handler for them (i.e. notepad++)... in the MarkdownMonster.json ` "sh": "bash", ` is present. Clicking on "Open with..." only gives a "once" option, and not an "always" option. Since I'm still in evaluation, I apparently can't modify the MM.json to add a handler
- [x] Crash: moving a directory that was within dropbox (just to another subfolder not "far away") NOTE: will file a bug if it happens reproducibly
- [x] Zettlr has a "MD Lint" included which can be nice but can also be annoying. Having a lint would be interesting for larger documents to avoid formatting mistakes... NOTE: agree, would make sense as an addon
- [x] outline numbering: when writing larger documents with many levels of headings, it's sometimes easy to get lost. It can be difficult to see in the preview which heading level you have (OK, can see that in the Markdown if synced). It is also difficult to see where in the overall structure you are. Outline numbering (like pandoc's "numbersections") would be great, both in the preview and (also optionally) in the TOC NOTE: see https://github.com/RickStrahl/MarkdownMonster/issues/1089

**Comment by RickStrahl** [comment]
These are good but I can't work on this in this format - I'd prefer these broken out by issues or related issues.

A quick note:

* Linting - not something I will add but if anybody is so inclined they can create an addin and do this.
* Crash - need repro scenarios.
* Equal tab widths - not going to happen as labels determine size. If there's one thing I hate it's truncated tabs in editors where you have to hover to find out what you're looking at :smile:
* Double-click - by design: First click opens in read-only mode, second click enters edit mode. Read mode is non-sticky, full edit mode is sticky.
* The others are good for separate issues.

**Comment by internationils** [comment]
No problem, will split out the relevant ones.
- Linting: makes sense as an addon
- Crash: only happened once
- Tab widths: maybe have a minimum size? Fully agree with truncated & hovering tooltips being "not nice" : )
- Double clicking: what does sticky mean in this context? Also: if second click enters edit mode, then it should be edit mode in the same tab

**Comment by internationils** [comment]
All topics are moved to their own issue, feel free to close, thanks!
